### PR TITLE
Passing Python Kwargs to Godot Envrionment

### PR DESCRIPTION
**Pull request by GianiStatie**
As Ivan wonderfully put it into words:

`custom arguments for launching the Godot env without calling a function, e.g. to set a different difficulty or do anything else with the env from Godot`

### CODE REVIEW

**Comment by GianiStatie** [comment]
This time it should work. I tested the flows locally before the commit 😅

**Review by edbeeching — COMMENTED** [review]
Looks great. Do you have an example env / code snippet of how a user would parse the args on the Godot side?

**Comment by GianiStatie** [comment]
I’m working on one, though it’s not yet published. 

I want to use the arguments to change the starting level such that people can skip those that the agent is too good on.

**Review by Ivan-267 — COMMENTED** [review]
It might be enough (for start) to have a short doc in the docs folder that explains the basic way to use the arguments (e.g. how to modify the sb3 training example to send a custom argument when training starts).

It should be enough for users to know how to pass the arguments during training, and how the argument can be accessed in Godot (this is generic, so you could even point to the doc). 

Different users would definitely have different use cases for this so it might not need to be overly abstracted initially (although we can later build on it as needed to add specific functionalities for specific use cases).

**Comment by GianiStatie** [comment]
Oh right, sure, I get it now. I’ll make the change tomorrow 👍

**Comment by GianiStatie** [comment]
I've added some info, hope it makes sense. I'm a bit rusty when it comes to writing docs as I don't exactly know who's the target audience 😅

**Review by edbeeching — APPROVED** [review]
Thanks for this change. LGTM. @GianiStatie would you like to be added as a contributor so making PRs is easier etc?

**Comment by GianiStatie** [comment]
hey @edbeeching 👋 sure, tho I can't promise to keep it at this pase 😆

**Pull request merged**
