### PR TITLE
Adds downfall env to tests and hub

### PR DESCRIPTION
**Pull request by edbeeching**

### CODE REVIEW

**Comment by Ivan-267** [comment]
Some of my examples had the default scene set to onnx inference for easier running, but it doesn't allow tests to work.

It will require updating the datasets on huggingface, e.g. https://huggingface.co/datasets/edbeeching/godot_rl_3DCarParking

**Comment by edbeeching** [comment]
Thanks @Ivan-267 , the tests seem to be working now. Ok to merge?

**Review by Ivan-267 — APPROVED** [review]
Not sure what's wrong with the windows tests. I'll rerun and check the results later.

**Comment by Ivan-267** [comment]
I've downloaded the envs from the hub manually and was able to reproduce the issue with BallChase.
I will try to find out the cause locally. 

Another thing to check after finding out the cause is why the linux tests are running fine.

**Comment by Ivan-267** [comment]
It works from the editor, but when running the prebuilt exe of e.g. BallChase, I get an error that the data folder including net assemblies is missing. It does work after that on my PC, but might cause the issue on the test server.

**Comment by edbeeching** [comment]
@Ivan-267 that fixed everything, thanks. Merging.

**Pull request merged**
