### PR TITLE
feat(multi discrete action spaces): added support for multi discrete action spaces

### PR DESCRIPTION
**Pull request by visuallization**
@edbeeching I added support for multi discrete action spaces so discrete action spaces > 2 can also be used with with stable baselines 3. What's your take on it? Is this alright or will it break anything in terms of rl algorithms?

### CODE REVIEW

**Comment by visuallization** [comment]
This also makes it work with clean-rl :)

**Comment by edbeeching** [comment]
Thanks for adding this implementation. It would great to also have an example environment to demonstrate and test this implementing on. I understand that this could be a lot of work. What environment would you imagine using multi-discrete space in ?

**Comment by visuallization** [comment]
I am currently using multi-discrete spaces like this:

https://github.com/visuallization/godot-4-ml-platformer/blob/main/environments/platformer/PlatformerAgent.gd

image

I know that you could also implement it in the way you did with Jumperhard where you used 2 continuous spaces and 1 discrete, but I like to have the flexibility. The cool thing with this is that it should also support then spaces n > 2. But it still needs some testing from my side.

Of course this also just applies if convert option is true. if not we just work directly with the dictionary and can have mixed spaces

**Review by edbeeching — APPROVED** [review]
LGTM

**Pull request merged**
